name       : msgpack
version    : 3.1.1
release    : 3
source     :
    - https://github.com/msgpack/msgpack-c/releases/download/cpp-3.1.1/msgpack-3.1.1.tar.gz : 8592d12e19ac3796889b8358bc8f78df9272e6aa7a9ea1834bafd68e4073549a
license    : BSL-1.0
component  : programming
summary    : An efficient object serialization library
description: |
    MessagePack is an efficient binary serialization format. It lets you exchange data among multiple languages like JSON. But it's faster and smaller. Small integers are encoded into a single byte, and typical short strings require only one extra byte in addition to the strings themselves.
builddeps  :
    - gtest-devel
setup      : |
    %cmake . \
        -DCMAKE_INSTALL_LIBDIR=%libdir% \
        -DMSGPACK_CXX11=ON
build      : |
    %make
install    : |
    %make_install
    rm $installdir/%libdir%/*.a
check      : |
    %make test
