name       : msgpack
version    : 1.4.1
release    : 1
source     :
    - https://github.com/msgpack/msgpack-c/releases/download/cpp-1.4.1/msgpack-1.4.1.tar.gz : 8ac512f52b30572f0244d6f521847ef3c54a59097dc05b479ac282bf1374f22e
license    : Boost
summary    : An efficient object serialization library 
description: |
   An efficient object serialization library 
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
