name       : msgpack
version    : 1.4.2
release    : 1
source     :
    - https://github.com/msgpack/msgpack-c/releases/download/cpp-1.4.2/msgpack-1.4.2.tar.gz : c0f1da8462ea44b23f89573eff04a1f329bcff6fd80eb0d4b976d7f19caf1fa2
license    : Boost-1.0
component  : programming
summary    : An efficient object serialization library
description: An efficient object serialization library
setup      : |
    %configure --disable-static
    %cmake -DCMAKE_INSTALL_LIBDIR=%libdir% .
build      : |
    %make
install    : |
    %make_install
    rm $installdir/%libdir%/*.a
