name       : msgpack
version    : 3.3.0
release    : 4
source     :
    - https://github.com/msgpack/msgpack-c/archive/refs/tags/cpp-3.3.0.tar.gz : 754c3ace499a63e45b77ef4bcab4ee602c2c414f58403bce826b76ffc2f77d0b
license    : BSL-1.0
component  : programming
summary    : An efficient object serialization library
description: |
    MessagePack is an efficient binary serialization format. It lets you exchange data among multiple languages like JSON. But it's faster and smaller. Small integers are encoded into a single byte, and typical short strings require only one extra byte in addition to the strings themselves.
builddeps  :
    - gtest-devel
setup      : |
    %cmake . \
        -DCMAKE_INSTALL_LIBDIR=%libdir% \
        -DMSGPACK_CXX11=ON
build      : |
    %make
install    : |
    %make_install
    rm $installdir/%libdir%/*.a
check      : |
    %make test
